== https://adventofcode.com/2019/day/8[Space Image Format]

I think that's maybe the second or third time I ever actively used Python.
Significant spaces: Is this YAML in disguise ;)?

The idea of the solution: Split the input into chunks the size of the images dimensions, sort by number of zeros and take the first. Second star uses an image mask.

[source,python,numbered,indent=0]
----
include::Solution.py[]
----
<1> Create the layers by chunking the input at the given dimension (Please note the comment at the `chunk` method). `chunk` returns a generator. This can be iterated, but cannot be reseted. I need the list of layers twice, so I copy them into a list
<2> Create a sorted copy of that list (by the count of `0`)
<3> I use a dictionary for translating the image value
<4> Start with a transparent image as mask.
    Again. we find a _list comprehension_ during AoC
<5> Here, we wrap the final image, this time at the width and than join those lines together by `\n`

The image mask array could have been generated by unpacking the list like this `[*map(lambda item: "2", range(d))]`, but I like the list comprehension more.

NOTE: Run with `python3 Solution.py`.
      Tested with `Python 3.7.0`
