:jbake-type: page
:jbake-title: Über uns
:jbake-status: published
= Über uns

:icons: font

ifndef::imagesdir[:imagesdir: ]

== About

This site is based on and inspired by https://adventofcode.com[adventofcode.com].
It provides a platform for coders to solve the challenges created by Eric Wastl, the brain behind adventofcode, together and compare the results.

This website is a fan website and is not connected to adventofcode.com in any other way.

== Clipart

The used clipart and other images for the website is (c) presentermedia.com and licenced to ralf.d.mueller@gmail.com

== Imprint

The following text has to be included in sites provided from Germany by German citizens, due to our sometimes strange, inconsistent and user-unfriendly data privacy laws.

=== Anbieter

Ralf D. Müller (Frankfurt/Main)

=== Kontakt

Telefon: +49-176 23286925, e-Mail: ralf.d.mueller@gmail.com

=== Verantwortlich nach § 6 Abs.2 MDStV
Ralf D. Müller

=== Privacy Statement (Datenschutzerklärung)
Diese Website sammelt keine personenbezogenen Daten.

=== Geltungsbereich
Diese Datenschutzerklärung klärt Nutzer über die Art, den Umfang und Zwecke der Erhebung und Verwendung personenbezogener Daten durch den verantwortlichen Anbieter Dr. Gernot Starke, Willi-Lauf Allee 43, D-50858 Köln, Deutschland, Email (gegen Spam gesichert), Tel.: +49 177 7282570 auf dieser Website (im folgenden “Angebot”) auf.

Die rechtlichen Grundlagen des Datenschutzes finden sich im Bundesdatenschutzgesetz (BDSG) und dem Telemediengesetz (TMG).


=== Zugriffsdaten/ Server-Logfiles

Der Anbieter (beziehungsweise sein Webspace-Provider) erhebt Daten über jeden Zugriff auf das Angebot (so genannte Serverlogfiles). Zu den Zugriffsdaten gehören:

Name der abgerufenen Webseite, Datei, Datum und Uhrzeit des Abrufs, übertragene Datenmenge, Meldung über erfolgreichen Abruf, Browsertyp nebst Version, das Betriebssystem des Nutzers, Referrer URL (die zuvor besuchte Seite), IP-Adresse und der anfragende Provider.

Der Anbieter verwendet die Protokolldaten nur für statistische Auswertungen zum Zweck des Betriebs, der Sicherheit und der Optimierung des Angebotes. Der Anbieterbehält sich jedoch vor, die Protokolldaten nachträglich zu überprüfen, wenn aufgrund konkreter Anhaltspunkte der berechtigte Verdacht einer rechtswidrigen Nutzung besteht.

=== Kontaktaufnahme
Bei der Kontaktaufnahme mit dem Anbieter (zum Beispiel per Kontaktformular oder E-Mail) werden die Angaben des Nutzers zwecks Bearbeitung der Anfrage sowie für den Fall, dass Anschlussfragen entstehen, gespeichert.

=== Kommentare und Beiträge
Wenn Nutzer Kommentare im Blog oder sonstige Beiträge hinterlassen, werden ihre IP-Adressen gespeichert. Das erfolgt zur Sicherheit des Anbieters, falls jemand in Kommentaren und Beiträgen widerrechtliche Inhalte schreibt (Beleidigungen, verbotene politische Propaganda, etc.). In diesem Fall kann der Anbieter selbst für den Kommentar oder Beitrag belangt werden und ist daher an der Identität des Verfassers interessiert.

=== Widerruf, Änderungen, Berichtigungen und Aktualisierungen
Der Nutzer hat das Recht, auf Antrag unentgeltlich Auskunft zu erhalten über die personenbezogenen Daten, die über ihn gespeichert wurden. Zusätzlich hat der Nutzer das Recht auf Berichtigung unrichtiger Daten, Sperrung und Löschung seiner personenbezogenen Daten, soweit dem keine gesetzliche Aufbewahrungspflicht entgegensteht.

=== Quelle
Danke an Hr Rechtsanwalt Thomas Schwenke:
http://rechtsanwalt-schwenke.de/smmr-buch/datenschutz-muster-generator-fuer-webseiten-blogs-und-social-media/[Datenschutz-Muster von Rechtsanwalt Thomas Schwenke - I LAW it]
