== Hello, World

This is an over engineered "Hello, World" application written in Groovy, using Spring Boot and the reactive web stack.
Of course, one wouldn't need a framework for that, but since Ralf asked for it...  ¯\\_(ツ)_/¯.

Day 0 doesn't correspond to any of the official AoC puzzles.

The application defines a `HelloWorldController` as a top level Spring bean:

[source, groovy, numbered]
....
include::solution.groovy[tags=helloWorld]
....

The solutions shall print out a greeting.
I will call the above endpoint via Springs reactive `WebClient` and subscribe to the flow.
This is done in a Spring Application listener, reacting on `ApplicationReadyEvent`.
`ApplicationReadyEvent` is fired when the application is ready to serve requests:
After the flow ends, I'll define a completable future to shutdown the application context.
That needs to happen on a new thread, as it contains some blocking calls, which are not allowed in a reactive flow.

[source, groovy, numbered]
....
include::solution.groovy[tags=callingTheGreeter]
....

I connect everything in a top level class call `DemoApplication` and wire up the listener:

[source, groovy, numbered]
....
include::solution.groovy[tags=puttingItTogether]
....

By using Groovys "Grapes" (`@Grab('org.springframework.boot:spring-boot-starter-webflux:2.2.1.RELEASE')`), this gives a runnable Groovy script:

```
groovy -Dlogging.level.root=WARN -Dspring.main.banner-mode=OFF solution.groovy
```

I included some configuration variables to turn off logging and Springs Banner, so that the application outputs only the greeting.

Bear in mind that this solution fires up a complete web stack and therefore is slower than probably any other _Hello World_ program out there.
