= ONE: Docs-as-Code

:jbake-type: post
:jbake-date: 2019-11-29
:jbake-status: published
:jbake-tags: asciidoc, docs-as-code

_Docs-as-Code_ is the approach where you treat your documentation as code which means you store it along with your code and you "compile" it from a plain text format to HTML.

Within this repository, you can give this approach a try.
Whenever you store a `README.adoc` along with your code, the build will pick it up and render it on the website.

For instance the `README.adoc` for the JavaScript "Hello World" example created by `docToolchain` looks like this:

./day00/groovy/docToolchain/README.adoc
[source, aciidoc, numbered]
----
include::../../../../day00/groovy/docToolchain/README.adoc[]
----

and it is rendered https://aoc-2019.netlify.com/generated/coder/doctoolchain/generateddays#_day_00_groovy[on the webpage].

The `.adoc` format is just plain text but quite powerful.
Here are some examples:

== Headlines

[options="noheader",cols="2"]
|===
l|
== Level 1
=== Level 2
==== Level 3
a|
== Level 1
=== Level 2
==== Level 3

|===

== Basic Formatting

[options="noheader",cols="2"]
|===
l|
This is *bold*, _kursive_, `monospaced`
a|
This is *bold*, _kursive_, `monospaced`

|===

== Include Source

[options="noheader",cols="2"]
|===
l|

[source, groovy, numbered]
----
include::helloWorld.groovy[]
----

a|
[source, groovy, numbered]
----
println "*"*20
println "Hello World".center(20)
println "*"*20
----

|===
