= ONE: Docs-as-Code
:jbake-type: post
:jbake-date: 2019-11-29
:jbake-status: published
:jbake-tags: asciidoc, docs-as-code

_Docs-as-Code_ is the approach where you treat your documentation as code which means you store it along with your code and you "compile" it from a plain text format to HTML.

Within this repository, you can give this approach a try.
Whenever you store a `README.adoc` along with your code, the build will pick it up and render it on the website.

To give it a try on your local machine, just execute

```
./gradlew  generateIndex bake bakePreview
```

and the build will generate the website and start a server for you.
You can also get a powerful preview of your docs if you install the AsciiDoc plugin for your favourite Editor or IDE.

== Example

As an example, the `README.adoc` for the JavaScript "Hello World" example created by `docToolchain` looks like this:

./day00/groovy/docToolchain/README.adoc
[source, aciidoc, numbered]
-----
== Hello World

This solution is written in Groovy.

I will use my helper to read the input from a file:

[source, groovy, numbered]
....
\include::solution.groovy[tags=helper]
....

=== First Star

The solutions shall print out a greeting.
I will wrap this in a simple `helloWorld` method.

[source, groovy, numbered]
....
\include::solution.groovy[tags=starOne,!starTwo]
....

<1> this is where I call the helper method to read my input

[plantuml]
----
file input.txt
component readInput
component helloWorld
helloWorld -> readInput : calls
readInput -> input.txt : reads file
----

=== Second Star

There is no second star.
-----

and it is rendered https://aoc-2019.netlify.com/generated/coder/doctoolchain/generateddays#_day_00_groovy[on the webpage].

== About AsciiDoc

The `.adoc` format is just plain text but quite powerful.
Here are some examples:

=== Headlines

Just add some `=` in front of your line to get a headline

[options="noheader",cols="2"]
|===
l|
== Level 1
=== Level 2
==== Level 3
a|
== Level 1
=== Level 2
==== Level 3

|===

=== Basic Formatting

There are several text formatting styles available. 
Here are three examples:

[options="noheader",cols="2"]
|===
l|
This is *bold*, _kursive_, `monospaced`
a|
This is *bold*, _kursive_, `monospaced`

|===

=== Include Source

You don't have to copy & paste your source to your docs, just reference them:

[options="noheader",cols="2"]
|===
l|

[source, groovy, numbered]
----
include::helloWorld.groovy[]
----

a|
[source, groovy, numbered]
----
println "*"*20
println "Hello World".center(20)
println "*"*20
----

|===

=== Diagrams

And you even have https://plantuml.com/[plantUML] at hand - a powerful library which converts text into diagrams:

[options="noheader",cols="2"]
|===
l|

[plantuml]
----
[a] -> [b]
[b] -> [c]
[c] -> [a]
----

a|
[plantuml]
----
[a] -> [b]
[b] -> [c]
[c] -> [a]
----

|===

You can read more about AsciiDoc in the the https://asciidoctor.org/docs/user-manual/[AsciiDoc User Manual] and more about the Docs-as-Code approach at https://docs-as-co.de

Now try to document your solution with your own `README.adoc`!

